In [1]:
import pandas as pd

def get_sp500_symbols():
    sp_500_url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
    
    tables = pd.read_html(sp_500_url)
    sp_500 = tables[0]
    return sp_500['Symbol'].tolist()
    
get_sp500_symbols()

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'APO',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BK',
 'BA',
 'BKNG',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BLDR',
 'BG',
 'BXP',
 'CHRW',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CRWD',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DAY',
 'DECK',
 'DE',
 'DELL',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DASH',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ERIE',
 'ESS',
 'EL',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXE',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GDDY',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KKR',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LII',
 'LLY',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PLTR',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SW',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TER',
 'TSLA',
 'TXN',
 'TPL',
 'TXT',
 'TMO',
 'TJX',
 'TKO',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WY',
 'WSM',
 'WMB',
 'WTW',
 'WDAY',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [3]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.55-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\aac\anaconda3\lib\site-packages (from yfinance) (2.1.4)
Requirement already satisfied: numpy>=1.16.5 in c:\users\aac\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\aac\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\aac\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\aac\anaconda3\lib\site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\aac\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.17.9.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     --- ------------------------------------ 0.3/3.0 MB ? eta -:--:--
     ---------- ----------------------------- 0.8/3.0 MB 2.8 MB/s eta 0:00:01
     -------------------------------------- - 2.9/3.0 MB 6.5 MB/s eta 0:00:01
     ---------------------------------------- 3.0/3.0 MB 6.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\aac\anaconda3\lib\site-packages (from yfinance) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\aac\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aac\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\aac\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aac\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aac\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aac\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aac\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2025.1.31)
Requirement already satisfied: six>=1.5 in c:\users\aac\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Downloading yfinance-0.2.55-py2.py3-none-any.whl (109 kB)
Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.9-py3-none-any.whl size=139126 sha256=80dc63d0c80c4f307bae2485cbb0644e279a6ee537a454baad8db75485c98e6b
  Stored in directory: c:\users\aac\appdata\local\pip\cache\wheels\f4\14\e4\50c88c865833085aeb91e2bd40e3a683ff434806386b8ee7bc
Successfully built peewee
Installing collected packages: peewee, multitasking, yfinance
Successfully installed multitasking-0.0.11 peewee-3.17.9 yfinance-0.2.55
Note: you may need to restart the kernel to use updated packages.

In [4]:
import yfinance as yf

In [6]:
data = yf.download('AAPL', '2025-4-14','2025-4-18','id')
data

[*********************100%***********************]  1 of 1 completed

Price,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
Date,,,,,,,
2025-04-14,202.520004,0.0,212.940002,201.160004,211.440002,0.0,101352900
2025-04-15,202.139999,0.0,203.509995,199.800003,201.860001,0.0,51343900
2025-04-16,194.270004,0.0,200.699997,192.369995,198.360001,0.0,59732400
2025-04-17,196.979996,0.0,198.830002,194.419998,197.199997,0.0,51334300

In [13]:
data1 = yf.download('GOOGL', '2025-4-14','2025-4-18',interval='1h' , ignore_tz=True , progress=False)
data1

Price                     Close        High         Low        Open    Volume
Ticker                    GOOGL       GOOGL       GOOGL       GOOGL     GOOGL
Datetime
2025-04-14 09:30:00  161.119995  161.339996  159.263000  160.037003   7242329
2025-04-14 10:30:00  159.800003  161.720001  159.789993  161.110001   3839239
2025-04-14 11:30:00  158.160004  160.115005  157.845001  159.820007   3926447
2025-04-14 12:30:00  158.500000  159.024597  157.570007  158.149994   2305185
2025-04-14 13:30:00  159.520004  159.639999  158.130005  158.479996   1875855
2025-04-14 14:30:00  159.985001  160.389999  159.440002  159.520004   2210889
2025-04-14 15:30:00  159.110001  160.210007  158.770004  159.990005   4015160
2025-04-15 09:30:00  157.085007  159.649994  156.820099  159.125000   6105182
2025-04-15 10:30:00  156.789993  157.899994  156.770004  157.089996   3326881
2025-04-15 11:30:00  156.690002  157.210007  156.399994  156.785004   3026238
2025-04-15 12:30:00  155.479996  156.686005  155.250000  156.679993   2475900
2025-04-15 13:30:00  155.649994  156.115005  155.210007  155.470001   1767587
2025-04-15 14:30:00  155.848404  156.195007  155.630005  155.639999   1819923
2025-04-15 15:30:00  156.300003  156.550003  155.490005  155.854996   3707739
2025-04-16 09:30:00  154.429993  154.589294  152.630005  153.009995   4763388
2025-04-16 10:30:00  155.529999  155.880005  154.350006  154.399994   2626135
2025-04-16 11:30:00  154.949997  155.529999  154.460007  155.524994   2057737
2025-04-16 12:30:00  154.869995  155.287003  154.639999  154.929993   1574152
2025-04-16 13:30:00  153.460007  154.899399  152.589996  154.869995   3598374
2025-04-16 14:30:00  151.690002  153.449997  151.509995  153.440002   2923195
2025-04-16 15:30:00  153.320007  153.779999  151.740005  151.740005   4086655
2025-04-17 09:30:00  152.630005  154.679993  152.600006  154.210007   5033604
2025-04-17 10:30:00  150.690002  152.875000  148.500000  152.660004  10102275
2025-04-17 11:30:00  151.554993  151.830002  150.585007  150.679993   2587427
2025-04-17 12:30:00  150.990005  151.800003  150.720001  151.539993   2475835
2025-04-17 13:30:00  151.679993  152.190002  150.990005  150.990005   1805087
2025-04-17 14:30:00  151.065002  152.029999  150.720001  151.690002   3282867
2025-04-17 15:30:00  151.210007  151.494995  150.580002  151.065002   3006880

In [32]:
import yfinance as yf
from datetime import datetime , timedelta

def get_finance_data(symbol, start, end, interval):
    result = {}
    for symbols in symbol:
        data = yf.download(tickers=symbols, start=start, end=end, interval=interval)
        if not data.empty:
            result[symbols] = data 
    return result

fetched_data = get_finance_data(['AAPL', 'MSFT'], '2025-04-14', '2025-04-17', '1d')
print(fetched_data)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

{'AAPL': Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2025-04-14  202.520004  212.940002  201.160004  211.440002  101352900
2025-04-15  202.139999  203.509995  199.800003  201.860001   51343900
2025-04-16  194.270004  200.699997  192.369995  198.360001   59732400, 'MSFT': Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2025-04-14  387.809998  394.649994  384.209991  393.220001  19251200
2025-04-15  385.730011  391.890015  384.160004  388.510010  17199900
2025-04-16  371.609985  381.609985  368.000000  380.670013  21967800}

In [36]:
def transform_data(data, symbol):
    data.columns = [col[0] for col in data.columns]
    data = data.reset_index()
    print(data)

    data = data[data["Close"] != 0]
    data["symbol"] = symbol
    data['close_change'] = data['Close'].diff().fillna(0)
    data['close_pct_change'] = data['Close'].pct_change().fillna(0) * 100
    print(data)
    return data[['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'symbol', 'close_change', 'close_pct_change']]

def ingest_yfinance_data(symbol_data, final_table, interval):
    values = []
    for symbol in symbol_data:
        try:
            start_date = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
            end_date = datetime.now().strftime('%Y-%m-%d')
            data_dict = get_finance_data([symbol], start_date, end_date, interval)
            if symbol in data_dict:
                data = transform_data(data_dict[symbol], symbol)

                if not data.empty:
                    values.extend([tuple(x) for x in data.to_numpy()])
        except Exception as e:
            print(e)
            # error_logger.error(f"{symbol} transformation error: {str(e)}")

    # if values:
    #     insert_data_to_db(final_table, values)
ingest_yfinance_data(['AAPL','MSFT'],"",'1d')

[*********************100%***********************]  1 of 1 completed

        Date       Close        High         Low        Open     Volume
0 2025-04-14  202.520004  212.940002  201.160004  211.440002  101352900
1 2025-04-15  202.139999  203.509995  199.800003  201.860001   51343900
2 2025-04-16  194.270004  200.699997  192.369995  198.360001   59732400
3 2025-04-17  196.979996  198.830002  194.419998  197.199997   51334300
        Date       Close        High         Low        Open     Volume  \
0 2025-04-14  202.520004  212.940002  201.160004  211.440002  101352900
1 2025-04-15  202.139999  203.509995  199.800003  201.860001   51343900
2 2025-04-16  194.270004  200.699997  192.369995  198.360001   59732400
3 2025-04-17  196.979996  198.830002  194.419998  197.199997   51334300

  symbol  close_change  close_pct_change
0   AAPL      0.000000          0.000000
1   AAPL     -0.380005         -0.187638
2   AAPL     -7.869995         -3.893339
3   AAPL      2.709991          1.394961

[*********************100%***********************]  1 of 1 completed

        Date       Close        High         Low        Open    Volume
0 2025-04-14  387.809998  394.649994  384.209991  393.220001  19251200
1 2025-04-15  385.730011  391.890015  384.160004  388.510010  17199900
2 2025-04-16  371.609985  381.609985  368.000000  380.670013  21967800
3 2025-04-17  367.779999  374.320007  366.890015  373.750000  20943700
        Date       Close        High         Low        Open    Volume symbol  \
0 2025-04-14  387.809998  394.649994  384.209991  393.220001  19251200   MSFT
1 2025-04-15  385.730011  391.890015  384.160004  388.510010  17199900   MSFT
2 2025-04-16  371.609985  381.609985  368.000000  380.670013  21967800   MSFT
3 2025-04-17  367.779999  374.320007  366.890015  373.750000  20943700   MSFT

   close_change  close_pct_change
0      0.000000          0.000000
1     -2.079987         -0.536342
2    -14.120026         -3.660598
3     -3.829987         -1.030647

In [ ]:
def create_connection():
    conn_str = (
        r"DRIVER={SQL Server};"
        r"SERVER=KHR;"
        r"DATABASE=BikeStore;"
        r"Trusted_Connection=yes;"
    )

    try:
        conn = pyodbc.connect(conn_str)
        print("✅ Connected to SQL Server successfully!")
        return conn
    except Exception as e:
        print(f"❌ Error connecting to SQL Server: {e}")
        return None

def create_table_if_not_exists():
    conn = create_connection()
    if not conn:
        return

    cursor = conn.cursor()
    create_table_query = """
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='stock_prices' and xtype='U')
    CREATE TABLE stock_prices (
        trade_date DATETIME,
        close_price FLOAT,
        high_price FLOAT,
        low_price FLOAT,
        open_price FLOAT,
        volume BIGINT,
        symbol VARCHAR(10),
        close_change FLOAT,
        close_pct_change FLOAT
    )
    """
    try:
        cursor.execute(create_table_query)
        conn.commit()
        print("✅ Table ensured: stock_prices")
    except Exception as e:
        print(f"❌ Error creating table: {e}")
    finally:
        cursor.close()
        conn.close()

def get_sp500_tickers():
    tables = pd.read_html(SP500_URL)
    sp500_df = tables[0]
    return sp500_df['Symbol'].tolist()
def insert_data_to_db(table_name, values):
    conn = create_connection()
    if not conn:
        return

    cursor = conn.cursor()
    insert_query = f"""
    INSERT INTO {table_name} (
        trade_date, close_price, high_price, low_price, open_price,
        volume, symbol, close_change, close_pct_change
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"""

    try:
        cursor.executemany(insert_query, values)
        conn.commit()
        print(f"✅ Inserted {len(values)} rows into {table_name}")
    except Exception as e:
        print(f"❌ Error inserting data: {e}")
    finally:
        cursor.close()
        conn.close()